# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package*.json ./

# Install dependencies (skip prepare scripts)
RUN npm install --ignore-scripts

# Bundle app source
COPY . .

# Build the app
RUN npm run build

# Expose port if necessary (optional)
# EXPOSE 3000

# Start the server
CMD ["node", "build/index.js"]
