# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package.json first
COPY package.json ./

# Install all dependencies (need dev deps for TypeScript compilation)
RUN npm install

# Copy source code
COPY . .

# Build the TypeScript code
RUN npm run build

# Set transport mode to HTTP
ENV TRANSPORT=http

# Start the server directly with node
CMD ["node", "build/index.js"]
